#!/bin/zsh

# Get active window ID

_w_active_id=$(xprop -root 32x '\t$0' _NET_ACTIVE_WINDOW | cut -f 2 | sed 's/0x/0x0/')

# Get geometry of active window

typeset -A _w_active_geo
_w_active_geo=( $(wmctrl -l -G | grep -e $_w_active_id | awk '{ print "x",$3,"y",$4,"w",$5,"h",$6 }') )

# If x < 1920, window is on the 1st screen. Add 1920 to move it to the 2nd screen
# If x >= 1920, window is on the 2nd screen. Subtract 1920 to move it to the 1st screen

if [[ $_w_active_geo[x] -lt 1920 ]] {
    (( _w_active_geo[x] += 1920 ))
} else {
    (( _w_active_geo[x] -= 1920 ))
}

wmctrl -i -r $_w_active_id -e 0,$_w_active_geo[x],$_w_active_geo[y],$_w_active_geo[w],$_w_active_geo[h]

