#!/bin/zsh

setopt localoptions

chosen=$(pactl list short sinks | awk '{ print $1,$2,$7 }' | rofi -dmenu -l 2 -location 3 -width 30 -xoffset -5 -yoffset 30 -p "🎜 🎚" )

typeset -A sink
sink=( $( echo $chosen | awk '{ print "id",$1,"nm",$2 }' ) )

if [[ ! -z $sink[nm] ]]; then
    pactl set-default-sink $sink[nm]
    typeset -a inputs=( $(pactl list sink-inputs short | cut -f 1) )
    for input ( $inputs ); do pactl move-sink-input $input $sink[id]; done
fi

